### ISSUE TITLE
Help users run the binary

### ISSUE THREAD

**Issue by ankitnayan** [SigNoz/troubleshoot#1]
After building the binary a few steps remain for each scenario of usage.
- Download binary
- provide permissions to binary
- Run binary

Should we provide binary as artifact in releases?

Should we:
1. provide a script to do above 3 steps?
2. provide a docker image to run troubleshooting?

### Scenarios
1. SigNoz installed in VM and application running on local machine or same/different VM
2. SigNoz installed in VM and application running in another docker-compose in same/different VM
3. SigNoz and application both installed in K8s

**Comment by ankitnayan** [comment]
@prashant-shahi would need your help here. 
You can seek help from @pranay01 in confirming install instructions and scenarios and testing.

**Comment by prashant-shahi** [comment]
> Should we provide a script to do above 3 steps?

Yes, we can now run the one-liner below to download the troubleshoot binary:

```console
curl -sL https://raw.githubusercontent.com/SigNoz/troubleshoot/main/scripts/install.sh | bash
```

> Should we provide a docker image to run troubleshooting?

Yes, we can now.

For docker:
```console
docker run -it --rm signoz/troubleshoot checkEndpoint --endpoint=localhost:4317
```

For k8s:
```console
kubectl -n platform run troubleshoot --image=signoz/troubleshoot --restart='OnFailure' -i --tty --rm --command -- ./troubleshoot checkEndpoint --endpoint=otel-collector:4317
```

/cc @ankitnayan 
/cc @pranay01
